# Generated by Django 4.1.7 on 2023-03-07 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_profile_apelido'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='resumo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
