# Generated by Django 4.1.7 on 2023-03-28 22:18

from django.db import migrations
import filebrowser.fields


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_profile_resumo'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=filebrowser.fields.FileBrowseField(blank=True, max_length=200, null=True, verbose_name='Image'),
        ),
    ]
