# Generated by Django 4.1.7 on 2023-03-08 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
                ('location', models.CharField(blank=True, max_length=250, null=True)),
                ('create_date', models.DateTimeField(blank=True, null=True)),
                ('date', models.CharField(blank=True, choices=[('segunda', 'Segunda-Feira'), ('terca', 'Terça-Feira'), ('quarta', 'Quarta-Feira'), ('quinta', 'Quinta-Feira'), ('sexta', 'Sexta-Feira'), ('sabado', 'Sábado'), ('domingo', 'Domingo')], max_length=10, null=True)),
                ('hour', models.TimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Missão',
                'verbose_name_plural': 'Missões',
            },
        ),
    ]
